#include "coe_format.h"

void GenerateCoeFile(unsigned char * binary, FILE * output) {
	char intro[] = "; Coe file generated by cas for usage in the fpga\nmemory_initialization_radix = 16\nmemory_initialization_vector =\n";
	fwrite(intro, sizeof(char), strlen(intro), output);
	char * basestr = malloc(300000);
	const char * hex = "0123456789abcdef";
	char * pin = binary;
	char * pout = basestr;
	int i = 0;
    for(; i < 65535; ++i){
        *pout++ = hex[(*pin>>4)&0xF];
        *pout++ = hex[(*pin++)&0xF];
        *pout++ = ',';
		*pout++ = '\n';
    }
	pout -= 2;
	*pout++ = ';';
	*pout = '\0';
	fwrite(basestr, sizeof(char), strlen(basestr), output);
}
